name: Deploy to Go

on:
  workflow_dispatch:

jobs:
  deploy-go:
    name: Deploy Go Environment
    runs-on: ubuntu-latest
    environment: go

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create frontend .env file (GO)
        run: echo "${{ vars.ENV_FILE_FRONTEND_GO }}" > .env.go

      - name: Write Firebase service account JSON
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GO }}' > firebase-sa.json

      - name: Install Firebase tools
        run: npm install -g firebase-tools

      - name: Build FE (GO)
        run: npm run build:go

      - name: Firebase Deploy (GO)
        run: firebase deploy --project go
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-sa.json
